on:
  push:
    branches: [ "main" ]


concurrency:
  group: "maze-algorithms-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository data
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Build ui
        run: |
          export PUBLIC_BASE_PATH=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          npm ci
          npm run build
      - uses: actions/upload-artifact@v4
        name: Push build data
        with:
          name: build-data
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        name: Pull build data
        with:
          name: build-data
          path: out
      - name: Push code to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}